spring:
  application:
    name: Rental App
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
    contexts: dev
  datasource:
    url: jdbc:postgresql://192.168.1.120:5432/bit
    username: bituser
    password: bituser
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: dotne.dotne@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  servlet:
    context-path: "/api"
service:
  free-reservation:
    freeReservationTypes:
      - FUNERAL
      - FIRE_DEPARTMENT
email:
  enabled: false

sms:
  api-key: ${SMS_API_KEY:123}
  base-url: ${SMS_BASE_URL:123}
  recipient: ${SMS_RECIPIENT:123}
---
spring:
  config:
    activate:
      on-profile: samuel
  liquibase:
    contexts: dev,samuel
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: matej
  liquibase:
    contexts: dev
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: filip
  liquibase:
    contexts: dev
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: adrian
  liquibase:
    contexts: dev
---
spring:
  config:
    activate:
      on-profile: vatroslav
  liquibase:
    contexts: dev
